// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBook.Infrastructure;

#nullable disable

namespace PhoneBook.Migrations
{
    [DbContext(typeof(PhoneBookDbContext))]
    [Migration("20260606022815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PhoneBook.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Email = "browncoat@serenity.com",
                            FirstName = "Malcolm",
                            LastName = "Reynolds",
                            PhoneNumber = "1111111111"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Email = "companion@serenity.com",
                            FirstName = "Inara",
                            LastName = "Serra",
                            PhoneNumber = "2222222222"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Email = "book@serenity.com",
                            FirstName = "Shepherd",
                            LastName = "Book",
                            PhoneNumber = "3333333333"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Email = "vera@serenity.com",
                            FirstName = "Jayne",
                            LastName = "Cobb",
                            PhoneNumber = "4444444444"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Email = "mechanic@serenity.com",
                            FirstName = "Kaylee",
                            LastName = "Frye",
                            PhoneNumber = "5555555555"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Email = "awesomeDoctor@serenity.com",
                            FirstName = "Simon",
                            LastName = "Tam",
                            PhoneNumber = "6666666666"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Email = "miranda@serenity.com",
                            FirstName = "River",
                            LastName = "Tam",
                            PhoneNumber = "7777777777"
                        });
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.ContactCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uncategorized"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Friends"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.Contact", b =>
                {
                    b.HasOne("PhoneBook.Domain.Entities.ContactCategory", "Category")
                        .WithMany("Contacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.ContactCategory", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
